# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
