# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20171221_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2017, 12, 21, 23, 32, 56, 85078)),
        ),
    ]
