# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_order_odate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='static/img/1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2017, 12, 23, 5, 21, 56, 833666)),
        ),
    ]
