# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20171223_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2017, 12, 23, 5, 46, 33, 148250)),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='services/static/img/1.jpg', upload_to='services/static/img/'),
        ),
    ]
