# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20171223_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2017, 12, 23, 6, 0, 58, 931083)),
        ),
    ]
