# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20171224_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='odate',
            field=models.DateField(default=datetime.datetime(2017, 12, 24, 16, 22, 20, 105698)),
        ),
    ]
